# Generated by Django 3.1.6 on 2021-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210227_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
