# Generated by Django 3.1.6 on 2021-02-27 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210227_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='attemps',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
