# Generated by Django 3.1.6 on 2021-02-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210228_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
