# Generated by Django 3.1.6 on 2021-04-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210228_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='date_grade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
